vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix:         '%app.path.article_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
            delete_on_remove: true
            delete_on_update: true