controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
articles:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\ArticlesController::index